### PR TITLE
Feature cicd matlab actions

### PR DESCRIPTION
**Pull request by iAnyKey**
Added support of matlab actions in github: 

- now tests will be performed on every commit to the 'master' branch and on every pull request. 
- code coverage report will be generated afterwards

see [this pull request](https://github.com/iAnyKey/physical-units-for-matlab/pull/2) for example

### CODE REVIEW

**Comment by iAnyKey** [comment]
@sky-s Hey, are you here? :)

**Comment by sky-s** [comment]
> @sky-s Hey, are you here? :)

Sorry, I haven't checked in for a very long time and was not getting any email alerts. Hopefully I've fixed that with adjusted settings.

**Comment by iAnyKey** [comment]
@sky-s Would you like to merge the CI/CD functionality I implemented here for automatic testing?

**Review by sky-s — APPROVED** [review]

**Comment by sky-s** [comment]
Reverts sky-s/physical-units-for-matlab#6

Seems to always fail:


Run MATLAB Tests and Generate Artifacts
Error: The process '/home/runner/work/_actions/matlab-actions/run-tests/v1/dist/bin/glnxa64/run-matlab-command' failed with exit code 1

Run MATLAB Tests and Generate Artifacts
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, 5monkeys/cobertura-action@master. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by iAnyKey** [comment]
> Reverts #6
> 
> Seems to always fail:
> 
> Run MATLAB Tests and Generate Artifacts Error: The process '/home/runner/work/_actions/matlab-actions/run-tests/v1/dist/bin/glnxa64/run-matlab-command' failed with exit code 1
> 
> Run MATLAB Tests and Generate Artifacts Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, 5monkeys/cobertura-action@master. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.


This has to do with older Node version 12 of the actions Checkout, Matlab-setup and Matlab-run-tests. #7  fixes the issue.
However the tests on your master are broken :)

**Pull request merged**
